AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSecretName:
    Type: String
    Description: "AWS Secrets Manager secret name for database credentials"

Resources:
  SpringBootLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MySpringBootLambda
      Handler: com.example.form_flow_backend.StreamLambdaHandler::handleRequest
      Runtime: java21
      MemorySize: 1024
      Timeout: 30
      CodeUri: .
      Environment:
        Variables:
          DB_SECRET_NAME: !Ref DBSecretName
      Policies:
        - AWSSecretsManagerGetSecretValuePolicy:
            SecretArn: !Sub "arn:aws:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:${DBSecretName}"
      Events:
        ApiGateway:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
