AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Parameters:
  DBSecretName:
    Type: String
    Description: "AWS Secrets Manager secret name for database credentials"

Resources:
  # Step 1: Define API Gateway separately
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: FormFlowApi
      StageName: Prod
      DefinitionBody:
        swagger: "2.0"
        info:
          title: "Form Flow API"
          version: "1.0"
        schemes:
          - "https"
        paths:
          /{proxy+}:
            x-amazon-apigateway-any-method:
              produces:
                - "application/json"
              parameters:
                - name: "proxy"
                  in: "path"
                  required: true
                  type: "string"
              responses: {}
              x-amazon-apigateway-integration:
                uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${SpringBootLambdaFunction.Arn}/invocations"
                httpMethod: "POST"
                type: "aws_proxy"

  # Step 2: Define Lambda function separately without direct API Gateway reference
  SpringBootLambdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: MySpringBootLambda
      Handler: com.example.form_flow_backend.FormFlowBackendApplication::handleRequest
      Runtime: java21
      MemorySize: 1024
      Timeout: 30
      CodeUri: .
      Policies:
        - AWSLambdaBasicExecutionRole
      Environment:
        Variables:
          # Avoid directly referencing API Gateway to break dependency cycle
          API_GATEWAY_URL: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/Prod"

  # Step 3: Create API Gateway deployment separately
  ApiGatewayDeployment:
    Type: AWS::ApiGateway::Deployment
    Properties:
      RestApiId: !Ref ApiGateway
      StageName: Prod
    DependsOn:
      - ApiGateway
      - SpringBootLambdaFunction

  # Step 4: Define Lambda Permission for API Gateway
  LambdaApiGatewayPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: "lambda:InvokeFunction"
      FunctionName: !Ref SpringBootLambdaFunction
      Principal: "apigateway.amazonaws.com"
      SourceArn: !Sub "arn:aws:execute-api:${AWS::Region}:${AWS::AccountId}:${ApiGateway}/*/*/{proxy+}"