name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest

    env:
      DB_SECRET_NAME: ${{ secrets.DB_SECRET_NAME }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set Up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Grant Execute Permission for Gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build --no-daemon --scan

      - name: Run Tests
        run: ./gradlew test --no-daemon

  cd:
    runs-on: ubuntu-latest
    needs: ci

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 21
          cache: gradle

      - name: Grant Execute Permission to Gradle Wrapper
        run: chmod +x gradlew

      - name: Build JAR with Gradle
        run: ./gradlew clean bootJar -x test

      - name: Generate Deployment Package
        run: |
          mkdir deploy
          cp build/libs/*.jar deploy/
          cd deploy
          zip -r deploy.zip ./*

      - name: Configure AWS Credentials
        run: |
          aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws configure set region ${{ secrets.AWS_REGION }}

      - name: Upload Deployment Package to S3
        run: |
          aws s3 cp deploy/deploy.zip s3://form-flow-bucket/deploy/backend/deploy.zip

      - name: Deploy to Elastic Beanstalk
        run: |
          VERSION_LABEL="v-$(date +%Y%m%d%H%M%S)"
          
          aws elasticbeanstalk create-application-version \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --version-label "$VERSION_LABEL" \
            --source-bundle S3Bucket="form-flow-bucket",S3Key="deploy/backend/deploy.zip"
          
          aws elasticbeanstalk update-environment \
            --application-name ${{ secrets.EB_APPLICATION_NAME }} \
            --environment-name ${{ secrets.EB_ENVIRONMENT_NAME }} \
            --version-label "$VERSION_LABEL" \